import { useEffect, useState } from 'react';
import Layout from '../../components/Layout';

const API = 'http://localhost/PMTS/backend/bid_opening';

export default function BidOpeningMinutes() {
  const [procurementId, setProcurementId] = useState('1');
  const [form, setForm] = useState({ bidder_name: '', bid_price_without_vat: '', vat_amount: '', bid_price_with_vat: '', bid_security_status: 'not_submitted', bank_name: '', security_amount: '', remarks: '' });
  const [records, setRecords] = useState([]);
  const [message, setMessage] = useState('');
  const load = async () => { const res = await fetch(`${API}/get_minutes.php?procurement_id=${procurementId}`); const data = await res.json(); setRecords(data.minutes || []); };
  useEffect(()=>{ load(); }, [procurementId]);
  const save = async e => { e.preventDefault(); const res = await fetch(`${API}/create_minutes.php`, {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({...form, procurement_id: procurementId})}); const data = await res.json(); setMessage(data.message || 'Saved'); if(data.success){ setForm({ bidder_name: '', bid_price_without_vat: '', vat_amount: '', bid_price_with_vat: '', bid_security_status: 'not_submitted', bank_name: '', security_amount: '', remarks: '' }); load(); }};
  return <Layout><div className="page-wrapper animate-fade-in"><div className="page-title"> Bid Opening Minutes</div><div className="page-subtitle">Record bidder prices, VAT, bid security and opening remarks</div>{message && <div className="alert alert-success">{message}</div>}<div className="card" style={{padding:20}}><form onSubmit={save} className="form-grid"><label>Procurement ID<input value={procurementId} onChange={e=>setProcurementId(e.target.value)} /></label><label>Bidder Name<input value={form.bidder_name} onChange={e=>setForm({...form,bidder_name:e.target.value})} required /></label><label>Price Without VAT<input type="number" value={form.bid_price_without_vat} onChange={e=>setForm({...form,bid_price_without_vat:e.target.value})} /></label><label>VAT Amount<input type="number" value={form.vat_amount} onChange={e=>setForm({...form,vat_amount:e.target.value})} /></label><label>Price With VAT<input type="number" value={form.bid_price_with_vat} onChange={e=>setForm({...form,bid_price_with_vat:e.target.value})} /></label><label>Bid Security<select value={form.bid_security_status} onChange={e=>setForm({...form,bid_security_status:e.target.value})}><option value="submitted">Submitted</option><option value="not_submitted">Not Submitted</option><option value="expired">Expired</option></select></label><label>Bank Name<input value={form.bank_name} onChange={e=>setForm({...form,bank_name:e.target.value})} /></label><label>Security Amount<input type="number" value={form.security_amount} onChange={e=>setForm({...form,security_amount:e.target.value})} /></label><label>Remarks<textarea value={form.remarks} onChange={e=>setForm({...form,remarks:e.target.value})} /></label><button className="btn btn-primary" type="submit">Save Minutes</button><button className="btn" type="button" onClick={()=>window.print()}>Print</button></form></div><div className="card" style={{padding:20, marginTop:20}}><table className="data-table"><thead><tr><th>Bidder</th><th>Without VAT</th><th>VAT</th><th>With VAT</th><th>Security</th><th>Bank</th><th>Security Amount</th><th>Remarks</th></tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.bidder_name}</td><td>{r.bid_price_without_vat}</td><td>{r.vat_amount}</td><td>{r.bid_price_with_vat}</td><td>{r.bid_security_status}</td><td>{r.bank_name}</td><td>{r.security_amount}</td><td>{r.remarks}</td></tr>)}</tbody></table></div></div></Layout>;
}